/* ==========================================================================
   Factbox — the onboarding. Five screens, three questions, on /join.

   ---------------------------------------------------------------------------
   WHAT THIS IS FOR, WHICH DECIDES EVERY QUESTION BELOW

   A reader arrives here from a story they were already reading. Their intent
   is "I want to keep reading." Everything between tapping the button and
   getting back to that story must either teach us something we will actually
   use, or increase their trust. Anything else is removed.

       Do not optimise for having an onboarding flow.
       Optimise for preserving intent.

   That is why this file is smaller than it was. The flow was eleven screens
   and six questions; it is five screens and three questions, and the entry
   screen IS the first question rather than a standalone promise before it.

   FOUR SCREENS WERE DELETED, not moved: the standalone intro, and the
   barrier, scrolling-habit and three-months-from-now questions. Nothing on
   this site read any of those three answers. They cost the reader three
   screens and about fifteen seconds and bought a column in a report nobody
   opened.

   Their SETTERS still exist — FBA.setBarrier / setScrolling / setFuture, and
   their vocabularies in js/account.js — because js/profile-sync.js's WATCHED
   list names all three and wrap() replaces a property that has to be there.
   What is gone is their USE. Nothing here calls them, nothing here asks the
   questions, and the record simply never gains those three fields.

   ---------------------------------------------------------------------------
   WHY THIS FILE IS CALLED start.js AND RUNS ON /join

   /join is where the traffic lands: /firststory, /story and /cleopatra all
   call to action at `/join?from=story`, those three pages are GENERATED by
   tools/compose.py, and tools/check-regressions.js fails the build if that
   link ever changes. The money is there too, so moving the questions would
   put a navigation in the middle of the funnel. js/gate.js's JOIN_URL and
   js/acct.js's "Create account" both already point at /join.

   The ENGINE stays at js/start.js for one reason that is also not a
   preference: five of the thirteen guards in tools/check-analytics.js read
   this exact path for the onboarding events, the per-question dwell and the
   abandon. So the file keeps its name and the events keep theirs —
   start_step, start_answer, start_abandon, start_ready.

   ES5 only. Every reader arrives through the Instagram or TikTok in-app
   webview: no let, no const, no arrows, no template literals, no
   URLSearchParams, no findIndex. Same rule as every file here except
   js/auth.js.

   ---------------------------------------------------------------------------
   THE FIVE

      1  interests   Q1. MULTI-select, max 2. THE ENTRY SCREEN.
                     Carries the promise about their story, and the one
                     "Already have an account? Sign in" in the whole flow.
      2  motivation  Q2. single-select, AUTO-ADVANCES
      3  affirm      not a question — one counted number (see below)
      4  goal        Q3. single-select, AUTO-ADVANCES
      5  ready       their own answers, their own story, the way ON to an
                    account, and the way BACK to the story under it

   SINGLE-SELECT AUTO-ADVANCES, after ADVANCE_MS, and the selection is marked
   BEFORE the timer is set so the confirmation is visible first. Multi-select
   keeps a Continue, because "up to 2" has no moment the machine can identify
   as finished.

   BACK NEVER AUTO-ADVANCES. That is the bug this discipline exists to
   prevent: an earlier version of this flow had a Back arrow that moved
   FORWARD, because the timer set by the tap that left the screen was never
   cancelled. So:

     * there is exactly one function that changes the screen, show_(i), and
       it takes an index — never "the next one";
     * it calls clearTimers() before it does anything else, which bumps a
       generation token so every timer still in flight becomes a no-op;
     * only a fresh tap inside the delegated click handler ever schedules an
       advance. Repainting a stored answer on load marks the button and
       schedules nothing.

   BACK NEVER WIPES ANYTHING. Nothing in this file clears an answer; the
   selected state lives on the buttons and is repainted from the store.

   ---------------------------------------------------------------------------
   THE STORY THEY CAME FROM, AND HOW IT IS CARRIED

   Two carriers, one fact, and both already existed:

     ?s=<id>        js/recommend.js's joinFor() appends it to js/gate.js's
                    joinURL(), so the paywall's CTA is /join?from=paywall&s=44.
                    read.html's script-less fallback builds the same URL.
     fb_return_v1   localStorage, {s:"44", at:<ms>}. read.html writes it
                    before handing a buyer to Stripe, because a query string
                    does not survive the trip out and back. This file writes
                    it too, from ?s=, so /join does not depend on another page
                    having run first.

   The query string is always believed: it came from the tap that got here.
   The stored one is believed for RETURN_MAX_AGE and no longer, because "your
   story isn't going anywhere" said over a story somebody read last week is a
   false sentence, and this flow's whole claim is that it is a true one.

   What the id buys: the story is recognisable behind the sheet, the result
   screen names it, and the last button goes to /read?s=<id> — that exact
   story, not home, not Explore, not a feed.

   IT SURVIVES A REFRESH. The answers survive because they are in FBA. The
   story survives because it is in the URL and in localStorage. And so does
   the RESULT SCREEN, which nothing else here would give you: showing it
   stamps finishOnboarding(), and the router in join.html would then send a
   reload to the money side — so the one screen carrying the way back to
   their story would be the one screen a refresh destroys. Showing it also
   writes a sessionStorage marker the router reads, and the CTA clears that
   marker on its way out, so a reload of the result screen IS the result
   screen and a later visit to /join is the plan.

   ---------------------------------------------------------------------------
   WHERE THE ANSWERS GO

   Through window.FBA — js/account.js — the store /join has always used: one
   localStorage key, one cookie mirror, and js/profile-sync.js copying it to
   customers/{uid}/profile/onboarding for a signed-in reader. No new key, no
   new Firestore path, no second store.

       Q1 interests  -> FBA.setInterests(list)   the `interests` array
       Q2 motivation -> FBA.setMotivation(k)     MOTIVES
       Q3 goal       -> FBA.setGoal(n)           GOALS: 5 | 10 | 15
       screen 5      -> FBA.finishOnboarding()

   Q1 STORES REAL TAXONOMY KEYS. js/account.js documents `i` as "an array of
   stacks.json topic keys", and the eleven-screen flow put invented keys in it
   instead — powerful_people, betrayal, how_we_got_here — a private vocabulary
   no ranking, shelf or recommendation could ever read. The four options below
   are groups of the REAL topic keys published on window.FBTAX, and what is
   stored is the group expanded: picking "The Bible, up close" stores
   ["new_testament","old_testament"]. js/recommend.js scores a same-topic
   story at 120 against a same-kind story at 45, so topic is both the field
   this record documents and the strongest signal the recommender has.

   Q3 STORES 15 WHEN THE READER TAPS 15. That number is not in the iOS
   DailyGoal enum, so the previous screen offered 20 instead — 15 would have
   clamped to 0, which is this store's word for "nobody answered". The
   vocabulary in js/account.js gained 15 rather than the screen losing it; the
   whole argument is written above GOALS there.

   ---------------------------------------------------------------------------
   NOTHING HERE TOUCHES MONEY. This file does not name a price, a plan or the
   trial, and it does not read or write FBA.plan(), FBA.checkoutURL() or
   anything else in js/account.js's money half. The two functions it is
   allowed to call on the other side of the page are window.FBJN.login() and
   window.FBJN.plans(), and both of them simply hand over the screen.
   ========================================================================== */

(function () {
  "use strict";

  var D = document;

  /* ======================================================================
     THE NUMBER ON THE AFFIRMATION SCREEN.  READ ALL OF THIS.

     The screen was specified as "N% of Factbox readers say they remember more
     of what they learn". NO SUCH RESEARCH EXISTS. No survey has been run, and
     the product measures neither recall nor confidence, so there is nothing to
     run one against. A page that tells a prospective customer a fabricated
     fact about existing customers, on the way to taking their money, is worse
     than any bug this flow could ship.

     So the claim is one constant, and its default is null.

       null  ->  the screen shows a number that is COUNTED, live, out of
                 data/index.json: how many cards there are. 450 today. It is
                 true, it is checkable, and it makes no claim about anybody.
                 This is what ships.

       a number  ->  the screen becomes the survey sentence instead. DO NOT set
                 it until a real survey has been run and you can name it. There
                 is deliberately no plausible-looking default to leave in by
                 accident: the failure mode of forgetting this constant is a
                 true sentence about the corpus, not a false one about people.

     tools/drive-start.js fails if a percent sign reaches that screen while
     this is null. That check is the point of it.
     ====================================================================== */
  var RECALL_CLAIM_PCT = null;

  /* The sentence that goes with a real figure, if there ever is one. Kept
     next to the constant so the two cannot drift apart. */
  var RECALL_CLAIM_TEXT = "of Factbox readers say they remember more of what they learn.";

  /* How long a single-select answer is left visibly confirmed before the
     screen moves. Under 250ms the tick has not finished drawing and the screen
     reads as having jumped; over 400ms it reads as a wait. */
  var ADVANCE_MS = 320;

  /* The screens, in order. The only ordering in this file. */
  var SCREENS = ["interests", "motivation", "affirm", "goal", "ready"];

  /* Which of them are questions, and which number each one is. */
  var QNUM = { interests: 1, motivation: 2, goal: 3 };

  /* The reader-facing question each screen asks, as a stable key. Reused as
     the `question` parameter so a report reads "goal" rather than "q3". */
  var QKEY = { interests: "interests", motivation: "motivation", goal: "goal" };

  /* The only screen with no Back arrow is the first: inside this flow there is
     nothing behind it. */
  var NO_BACK = { interests: 1 };

  /* The two single-select screens. Tapping one of these advances the flow. */
  var AUTO = { motivation: 1, goal: 1 };

  /* At most two answers to Q1. A third tap on a fresh option does nothing
     rather than silently evicting an answer the reader gave on purpose; the
     unpicked cards go visibly inert once the cap is reached, so the screen
     says why instead of feeling broken. */
  var MAX_INTERESTS = 2;

  /* ======================================================================
     Q1'S OPTIONS, AND THE TOPIC KEYS UNDER THEM.

     `k` is the data-k in join.html and the value that reaches start_answer.
     `topics` are data/index.json topic keys — the same keys window.FBTAX
     names and js/recommend.js scores against — and they are what is STORED.

     Four groups, every one of the eight real topics in exactly one of them,
     and no story out of reach:

       ancient  cleopatra 8 + ancient_world 4                 = 12 stories
       bible    new_testament 11 + old_testament 7            = 18 stories
       church   church_history 11                             = 11 stories
       modern   medieval_modern 5 + us_history 4 + disaster 1 = 10 stories

     The labels are FBTAX's own names and its own notes, shortened. They are
     not invented categories laid over the corpus: every one of them is a
     heading this site already uses about itself.
     ====================================================================== */
  var Q1 = [
    { k: "ancient", topics: ["cleopatra", "ancient_world"],
      label: "Cleopatra and the ancient world" },
    { k: "bible",   topics: ["new_testament", "old_testament"],
      label: "the Bible, up close" },
    { k: "church",  topics: ["church_history"],
      label: "saints and sinners" },
    { k: "modern",  topics: ["medieval_modern", "us_history", "disaster"],
      label: "medieval and modern" }
  ];

  function q1Row(k) {
    var i;
    for (i = 0; i < Q1.length; i++) { if (Q1[i].k === k) return Q1[i]; }
    return null;
  }

  /* ======================================================================
     Reader-facing labels for the keys that get said back on the last screen.
     The keys themselves are the data-k attributes in join.html.
     ====================================================================== */

  var MOTIVE_LABEL = {
    smarter:        "Feeling smarter every day",
    understand:     "Actually understanding history",
    conversation:   "Better things to talk about",
    less_scrolling: "Something better than scrolling"
  };

  /* Keyed by minutes. 15 is here because js/account.js's GOALS now contains
     15; a missing row would print a number the reader did not pick. */
  var GOAL_LABEL = { "5": "5 minutes a day", "10": "10 minutes a day",
                     "15": "15 minutes a day" };

  /* ======================================================================
     Guarded primitives. Nothing in here may throw at top level; a page that
     throws before it shows a screen is a page with no words on it.
     ====================================================================== */

  function el(id) { try { return D.getElementById(id); } catch (e) { return null; } }

  function on(node, ev, fn) {
    try { if (node && node.addEventListener) node.addEventListener(ev, fn, false); }
    catch (e) {}
  }

  function show(node, yes) {
    try { if (node) { if (yes) node.removeAttribute("hidden"); else node.setAttribute("hidden", "hidden"); } }
    catch (e) {}
  }

  function text(node, s) {
    try { if (node) node.textContent = String(s == null ? "" : s); } catch (e) {}
  }

  function addClass(node, c) {
    try {
      if (!node) return;
      var cur = " " + (node.className || "") + " ";
      if (cur.indexOf(" " + c + " ") === -1) {
        node.className = ((node.className || "") + " " + c).replace(/^\s+/, "");
      }
    } catch (e) {}
  }
  function removeClass(node, c) {
    try {
      if (!node) return;
      node.className = (" " + (node.className || "") + " ")
        .replace(" " + c + " ", " ").replace(/^\s+|\s+$/g, "");
    } catch (e) {}
  }

  function bodyClass(c, yes) {
    try { if (yes) addClass(D.body, c); else removeClass(D.body, c); } catch (e) {}
  }

  function opts(id) {
    var box = el(id), out = [], i;
    if (!box) return out;
    try {
      var kids = box.getElementsByTagName("button");
      for (i = 0; i < kids.length; i++) out.push(kids[i]);
    } catch (e) {}
    return out;
  }

  function A() {
    try { return (window.FBA && typeof window.FBA.setGoal === "function") ? window.FBA : null; }
    catch (e) { return null; }
  }

  function track(nm, extra) {
    try { if (window.FB && window.FB.track) window.FB.track(nm, extra); } catch (e) {}
  }

  /* ======================================================================
     MEASURING THE FUNNEL.

     Four event names, all literal — start_step, start_answer, start_abandon,
     start_ready. Not `start_interests`, not `answer_<key>`: GA4 caps distinct
     event names and reports badly long before the cap, so the question and the
     answer are PARAMETERS.

     NOTHING TYPED IS SENT. `answer` is a button's data-k, one of a fixed list
     written into join.html. There is no text input anywhere in these five
     screens — no name, no email, no search box — and nothing in this file
     reads an input's value. The sign-up form on the same page belongs to the
     other script and is never touched from here.

     EVERY PARAMETER IS BOUNDED: values clipped to GA4's 100 characters, dwells
     to half an hour, so a phone left on a question overnight reports a ceiling
     rather than a number that ruins an average.

     NOTHING HERE MAY THROW OR DELAY A TAP. Every call is wrapped, and the
     measurement happens after the answer has been marked and stored.
     ====================================================================== */

  var DWELL_MAX = 1000 * 60 * 30;   /* half an hour is not a question */

  function nowMs() {
    try { return Date.now(); } catch (e) { return 0; }
  }

  function clip(v, n) {
    try {
      var t = String(v == null ? "" : v);
      return t.length > n ? t.slice(0, n) : t;
    } catch (e) { return ""; }
  }

  var screenAt = 0;      /* when the screen on display was shown */
  var shown    = false;  /* has any screen been shown yet */
  var answers  = {};     /* which questions have been answered */
  var readyHit = false;  /* the result screen was reached: not an abandon */
  var leftSaid = false;  /* start_abandon is reported once, like stack_dropoff */

  /* Time on the screen currently displayed. */
  function dwell() {
    try {
      if (!screenAt) return 0;
      var ms = nowMs() - screenAt;
      if (ms < 0) return 0;
      return ms > DWELL_MAX ? DWELL_MAX : ms;
    } catch (e) { return 0; }
  }

  function answerCount() {
    var n = 0, k;
    try { for (k in answers) if (Object.prototype.hasOwnProperty.call(answers, k)) n++; }
    catch (e) {}
    return n;
  }

  /* ======================================================================
     What the reader has told us.

     All three are written straight through to FBA the moment they are tapped,
     and read back out of FBA on load. `picks` is the copy these screens render
     from, not a second store: it is repopulated from the record by repaint(),
     and nothing here is the only place an answer lives.
     ====================================================================== */

  var picks = { interests: [], motivation: "", goal: "" };

  function hasInterest(k) {
    try { return picks.interests.indexOf(k) !== -1; } catch (e) { return false; }
  }

  /* The chosen option keys, expanded into the real topic keys, in the order
     they were picked. That expansion is the whole reason this indirection
     exists: the buttons speak the reader's language, the record speaks
     data/index.json's. */
  function storeInterests() {
    try {
      var out = [], i, j, row;
      for (i = 0; i < picks.interests.length; i++) {
        row = q1Row(picks.interests[i]);
        if (!row) continue;
        for (j = 0; j < row.topics.length; j++) {
          if (out.indexOf(row.topics[j]) === -1) out.push(row.topics[j]);
        }
      }
      var a = A();
      if (a) a.setInterests(out);
    } catch (e) {}
  }

  /* Returns false when the tap changed nothing — the cap is reached and this
     is not one of the chosen. A no-op must not be measured as an answer. */
  function toggleInterest(k) {
    try {
      if (!q1Row(k)) return false;
      var i = picks.interests.indexOf(k);
      if (i !== -1) { picks.interests.splice(i, 1); }
      else {
        if (picks.interests.length >= MAX_INTERESTS) return false;
        picks.interests.push(k);
      }
      storeInterests();
      return true;
    } catch (e) { return false; }
  }

  function storeGoal(k) {
    try {
      var a = A();
      if (a) a.setGoal(Number(k) || 0);
    } catch (e) {}
  }

  function storeMotivation(k) {
    try {
      var a = A();
      if (a && typeof a.setMotivation === "function") a.setMotivation(k);
    } catch (e) {}
  }

  /* ======================================================================
     THE STORY THEY CAME FROM.

     Read from the query string first, then from the key read.html already
     writes. Sanitised to the shape a stack id actually has, because it goes
     into an href and into a comparison against the index.
     ====================================================================== */

  var RETURN_KEY     = "fb_return_v1";
  var RETURN_MAX_AGE = 1000 * 60 * 60 * 6;   /* six hours */
  var READY_KEY      = "fb_ob_ready_v2";     /* sessionStorage; see the header */
  var AT_KEY         = "fb_ob_at_v2";        /* sessionStorage; which screen */
  var FALLBACK_STORY = "01";                 /* free; see data/index.json */

  var origin = "";        /* the id, or "" */
  var originStack = null; /* its record out of data/index.json, once loaded */

  function cleanId(v) {
    try {
      var s = String(v == null ? "" : v);
      return /^[A-Za-z0-9_-]{1,12}$/.test(s) ? s : "";
    } catch (e) { return ""; }
  }

  /* Not URLSearchParams: absent on the older in-app webviews this site
     targets, and this runs on a top-level-reachable path. */
  function qs(name) {
    try {
      var m = new RegExp("[?&]" + name + "=([^&#]*)").exec(String(location.search || ""));
      return m ? decodeURIComponent(m[1].replace(/\+/g, " ")) : "";
    } catch (e) { return ""; }
  }

  function rememberOrigin(id) {
    try {
      localStorage.setItem(RETURN_KEY, JSON.stringify({ s: String(id), at: nowMs() }));
    } catch (e) {}
  }

  function storedOrigin() {
    try {
      var raw = localStorage.getItem(RETURN_KEY);
      if (!raw) return "";
      var o = JSON.parse(raw);
      if (!o) return "";
      var at = Math.floor(Number(o.at) || 0);
      /* A story read last week is not "your story". Saying that it is would be
         the one false sentence in a flow whose whole promise is that
         sentence. */
      if (!at || (nowMs() - at) > RETURN_MAX_AGE) return "";
      return cleanId(o.s);
    } catch (e) { return ""; }
  }

  function findOrigin() {
    var fromUrl = cleanId(qs("s"));
    if (fromUrl) { rememberOrigin(fromUrl); return fromUrl; }
    return storedOrigin();
  }

  function markReady() {
    try { sessionStorage.setItem(READY_KEY, origin || "1"); } catch (e) {}
  }
  function clearReady() {
    try { sessionStorage.removeItem(READY_KEY); } catch (e) {}
  }
  function pendingReady() {
    try { return sessionStorage.getItem(READY_KEY) || ""; } catch (e) { return ""; }
  }

  /* WHERE THEY WERE. An in-app webview reloads itself without being asked —
     SPEC.md 1 — and losing your place six screens in reads as losing your
     answers, even when every answer is still marked. Per tab, so a second tab
     starts at the beginning, and a number rather than a name so a screen that
     is renamed cannot resume onto a screen that no longer exists.

     Written on every show_, read once on boot, and CLAMPED there: see
     resumeAt(). */
  function markAt(i) {
    try { sessionStorage.setItem(AT_KEY, String(i)); } catch (e) {}
  }

  /* The furthest screen it is honest to put them back on.

     Never past a question they have not answered — landing on the goal screen
     with no motivation stored would skip a question and count it as asked —
     and never on the result screen, which stamps finishOnboarding() and is
     reached through its own marker instead. */
  function resumeAt() {
    var want = 0;
    try { want = Math.floor(Number(sessionStorage.getItem(AT_KEY)) || 0); } catch (e) { want = 0; }
    if (!(want > 0)) return 0;
    var allowed = 0;
    if (picks.interests.length) allowed = 1;
    if (picks.interests.length && picks.motivation) allowed = 3;
    if (want > allowed) want = allowed;
    if (want > SCREENS.length - 2) want = SCREENS.length - 2;
    return want < 0 ? 0 : want;
  }

  function storyHref(id) {
    return "/read?s=" + encodeURIComponent(id || FALLBACK_STORY);
  }

  /* May this reader actually open the story they came from?

     ONE QUESTION, ONE ANSWER: js/access.js decides, through js/gate.js's
     FB.unlocked(), the same as every other surface. This file does not keep a
     second opinion — four surfaces once answered it four ways and paying
     readers got padlocks.

     The `free` flag out of data/index.json is not a second opinion either; it
     is the other half of the question. A free story is open to everybody and
     a locked one is open to a subscriber, and both facts are needed before
     the last screen can know whether "back to the story" is a way back or a
     way round in a circle. */
  function unlockedNow() {
    try { if (window.FB && window.FB.unlocked) return !!window.FB.unlocked(); } catch (e) {}
    return false;
  }

  function originOpen() {
    /* No story: the last button falls back to story 01, which is free. */
    if (!origin) return true;
    /* The index has not landed yet. Assume open rather than pitching at a
       reader whose story may be free — the paint runs again when it does. */
    if (!originStack) return true;
    if (originStack.free) return true;
    return unlockedNow();
  }

  /* The story, behind the sheet, blurred and dimmed. Not decoration: it is the
     sentence "your story isn't going anywhere" made checkable. */
  function paintBehind() {
    var box = el("ob-behind");
    if (!box) return;
    if (!origin || !originStack) { show(box, false); bodyClass("ob-over", false); return; }
    try {
      var img = el("ob-behind-art");
      var key = String(originStack.img || "");
      if (img && key && !img.getAttribute("src")) {
        /* The same two-step every cover on this site uses: the full plate,
           falling back to the thumbnail, so a missing file is a smaller
           picture rather than a hole. */
        img.onerror = function () {
          try { this.onerror = null; this.src = "/img/thumbs/" + key + ".webp"; } catch (e) {}
        };
        img.src = "/img/stacks/" + key + ".webp";
      }
      text(el("ob-behind-title"), originStack.title || "");
    } catch (e) {}
    show(box, true);
    bodyClass("ob-over", true);
  }

  /* The promise at the top of screen 1, and the end of the flow. The promise
     is only made when there is a story to make it about. */
  function paintOrigin() {
    show(el("ob-promise"), !!origin);
    paintEnding();
    paintBehind();
  }

  /* Is there a Firebase account on this browser right now? Read, never
     driven: js/auth.js owns every part of signing anybody in, and this file
     only wants to know which word goes on a button. Absent SDK, signed out
     and "not answered yet" all read as false, which is the safe direction —
     the button then offers to make an account, and the account step skips
     itself the moment it finds a uid. */
  function signedIn() {
    try { return !!(window.FBU && window.FBU.uid && window.FBU.uid()); }
    catch (e) { return false; }
  }

  /* The last screen's controls.

     THE ORDER THE FUNNEL RUNS IN, and this is the screen where it is decided.
     /join is the sign-up funnel: the end of a free story, the paywall and the
     account menu all arrive here as a reader deciding whether to pay. So the
     primary control CONTINUES the funnel — it hands the screen to the account
     step, which is where an account is actually created, and the prices come
     after that. It used to hand over only when the story behind the sheet was
     locked, which left a reader who had just tapped "Sign up to read more" on
     a free story with no way forward at all.

     THE WAY BACK TO THEIR STORY IS NEVER TAKEN AWAY. It is the quiet second
     line under it, and it is an <a> with a real href, so declining to make an
     account is one tap and cannot trap anybody.

     THE ONE READER WHO IS NOT SOLD TO is one who already pays. For them the
     story link is the whole ending, because there is nothing to sell.

     WITH NO SCRIPT only #ob-ready-go is visible, because the other two ship
     hidden — so a script-less page still ends on a control that works. */
  function paintEnding() {
    var go = el("ob-ready-go"), buy = el("ob-ready-buy"), back = el("ob-ready-back");
    var mine = unlockedNow();
    try {
      if (go) {
        go.setAttribute("href", storyHref(origin));
        text(go, origin ? "Take me back to the story" : "Start my first story");
      }
      if (back) {
        back.setAttribute("href", storyHref(origin));
        text(back, origin ? "Not now \u2014 back to the story"
                          : "Not now \u2014 start a free story");
      }
      if (buy) text(buy, signedIn() ? "Pick my plan" : "Create my account");
    } catch (e) {}
    show(go, mine);
    show(buy, !mine);
    show(back, !mine);
  }

  /* ======================================================================
     The corpus. data/index.json, through js/gate.js's loader when it is on
     the page so this is the same request the shelves make.

     The affirmation number is counted out of it. It degrades to the count
     already in the markup, which is the same real number — a dead fetch costs
     the reader nothing on screen and cannot turn a true number into a false
     one, because the fallback IS the figure.
     ====================================================================== */

  var stacks = null;

  function loadIndex() {
    try {
      if (window.FB && window.FB.loadIndex) return window.FB.loadIndex();
    } catch (e) {}
    try {
      return fetch("/data/index.json", { cache: "force-cache" }).then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      }).then(function (d) {
        if (!d || !d.stacks || !d.stacks.length) throw new Error("empty index");
        return d.stacks;
      });
    } catch (e2) {}
    return null;
  }

  function cardCount() {
    var n = 0, i;
    if (!stacks || !stacks.length) return 0;
    for (i = 0; i < stacks.length; i++) {
      try { n += (stacks[i].cards && stacks[i].cards.length) ? stacks[i].cards.length : 0; }
      catch (e) {}
    }
    return n;
  }

  function stackById(id) {
    var i;
    if (!stacks || !stacks.length || !id) return null;
    for (i = 0; i < stacks.length; i++) {
      try { if (String(stacks[i].id) === String(id)) return stacks[i]; } catch (e) {}
    }
    return null;
  }

  /* The affirmation, painted. Two shapes, and which one you get is decided
     entirely by RECALL_CLAIM_PCT at the top of this file. */
  function paintAffirm() {
    var stat = el("ob-stat"), cap = el("sc-affirm-h"), note = el("ob-stat-note");
    var tail = "Turns out, learning sticks better when the story is actually " +
               "worth remembering.";
    if (RECALL_CLAIM_PCT !== null && RECALL_CLAIM_PCT !== undefined) {
      text(stat, String(RECALL_CLAIM_PCT) + "%");
      text(cap, RECALL_CLAIM_TEXT);
      text(note, tail);
      return;
    }
    /* The shipping shape: a count, not a claim. */
    var n = cardCount();
    if (n) text(stat, String(n));
    text(cap, "cards of history, written to be remembered rather than revised.");
    text(note, tail);
  }

  /* ======================================================================
     The screens.
     ====================================================================== */

  var idx = 0;
  var running = false;
  var advTimer = null;
  var histOK = false;
  /* A generation token. Leaving a screen bumps it and every timer still in
     flight becomes a no-op. This is the whole of "Back never auto-advances". */
  var runId = 0;

  function screenNode(i) { return el("sc-" + SCREENS[i]); }

  function clearTimers() {
    runId++;
    try { if (advTimer) { window.clearTimeout(advTimer); advTimer = null; } } catch (e) {}
  }

  function paintChrome() {
    var here = SCREENS[idx];
    show(el("ob-back"), !NO_BACK[here]);

    /* The bar is the whole step indicator. No "Step 3 of 5" anywhere. It is
       1-based over the count rather than 0-based over the gaps, so the first
       screen already shows progress — which is the screen that most needs to
       say "this is quick" — and the last one is full. */
    var bar = el("ob-track"), fill = el("ob-fill");
    show(bar, true);
    try {
      var pct = Math.round(((idx + 1) / SCREENS.length) * 100);
      if (fill) fill.style.width = pct + "%";
      if (bar) bar.setAttribute("aria-valuenow", String(idx + 1));
    } catch (e) {}
  }

  /* Move focus to the screen's heading so a screen reader announces it.
     Never to a control: the first render is the page loading, and taking
     focus there fights the browser rather than helping. */
  function focusHead(node) {
    try {
      if (!node) return;
      var h = node.getElementsByTagName("h1")[0] || node.getElementsByTagName("h2")[0];
      if (!h) return;
      h.setAttribute("tabindex", "-1");
      h.focus();
    } catch (e) {}
  }

  /* The one function that changes the screen. It takes an index. */
  function show_(i) {
    clearTimers();
    if (i < 0) i = 0;
    if (i > SCREENS.length - 1) i = SCREENS.length - 1;

    /* Read the outgoing screen BEFORE idx moves. Its dwell rides on the event
       for the screen being shown, which is how the affirmation screen gets
       measured without another event name: whatever the reader spent on the
       450 arrives as from_ms on the goal step. */
    var fromName = shown ? SCREENS[idx] : "";
    var fromMs   = shown ? dwell() : 0;
    idx = i;

    var j, node;
    for (j = 0; j < SCREENS.length; j++) {
      node = screenNode(j);
      show(node, j === i);
      if (node) removeClass(node, "is-in");
    }
    paintChrome();

    /* Top of the new screen. Set the property rather than calling
       window.scrollTo: the render check runs this file in jsdom, where
       scrollTo is a hard "not implemented", and a check that cries wolf on a
       page that renders perfectly is a check nobody runs. */
    try { if (D.documentElement) D.documentElement.scrollTop = 0; } catch (e) {}
    try { if (D.body) D.body.scrollTop = 0; } catch (e) {}

    var here = SCREENS[i];
    var node2 = screenNode(i);

    if (here === "affirm") paintAffirm();
    if (here === "ready")  enterReady();

    /* Restart the entrance animation. Reading offsetHeight between the two is
       what makes the browser treat it as a new animation rather than the same
       one continuing. */
    try {
      if (node2 && shown) { node2.offsetHeight; addClass(node2, "is-in"); }
    } catch (e2) {}

    if (shown) focusHead(node2);

    var p = { step: here, q: QNUM[here] || 0 };
    if (fromName) { p.from = fromName; p.from_ms = fromMs; }
    track("start_step", p);
    markAt(i);
    screenAt = nowMs();
    shown = true;
  }

  function go(i) {
    if (i === idx) return;
    if (histOK) {
      try { window.history.pushState({ fbs: i }, ""); } catch (e) {}
    }
    show_(i);
  }

  function back() {
    if (idx <= 0) return;
    if (histOK) {
      try { window.history.back(); return; } catch (e) {}
    }
    show_(idx - 1);
  }

  /* ======================================================================
     Answering.

     Tapping marks. On a single-select screen the mark is left visible for
     ADVANCE_MS and then the flow moves; on the multi-select screen Continue
     moves it. Every advance is scheduled against the generation token, so
     leaving the screen for any reason — Back, popstate, the money side taking
     over — cancels it.
     ====================================================================== */

  function setGo(id, enabled) {
    try {
      var b = el(id);
      if (!b) return;
      if (enabled) b.removeAttribute("disabled");
      else b.setAttribute("disabled", "disabled");
    } catch (e) {}
  }

  function markOne(id, k) {
    var list = opts(id), i, node, mine;
    for (i = 0; i < list.length; i++) {
      node = list[i];
      mine = node.getAttribute("data-k") === String(k);
      if (mine) addClass(node, "on"); else removeClass(node, "on");
      try { node.setAttribute("aria-checked", mine ? "true" : "false"); } catch (e) {}
    }
  }

  /* ======================================================================
     SAYING SO WHEN AN ANSWER IS ALREADY TICKED.

     A reader who has been through these questions before gets them again —
     from a story or from the paywall they are one tap past finishing a story,
     and a price list is the wrong first move. What they do not get is the
     work: repaint() marks everything they said last time, so the whole flow
     is a tap per screen to confirm or change.

     A ticked option with nothing said about it reads as broken, though, so
     each question carries one line that appears only when there is something
     to say. It goes the moment they tap on that screen, because from then on
     the tick is theirs and this session's.
     ====================================================================== */
  function knownNode(screen) { return el("ob-known-" + screen); }

  function paintKnown() {
    show(knownNode("interests"),  picks.interests.length > 0);
    show(knownNode("motivation"), !!picks.motivation);
    show(knownNode("goal"),       !!picks.goal);
  }

  /* Multi-select, with the cap made visible. At two answers the unchosen cards
     go inert and say so to assistive technology; they come back the moment one
     is released. */
  function markMany(id) {
    var list = opts(id), i, node, mine;
    var full = picks.interests.length >= MAX_INTERESTS;
    for (i = 0; i < list.length; i++) {
      node = list[i];
      mine = hasInterest(node.getAttribute("data-k"));
      if (mine) addClass(node, "on"); else removeClass(node, "on");
      if (!mine && full) addClass(node, "off"); else removeClass(node, "off");
      try {
        node.setAttribute("aria-pressed", mine ? "true" : "false");
        node.setAttribute("aria-disabled", (!mine && full) ? "true" : "false");
      } catch (e) {}
    }
  }

  /* Schedule the move to the next screen. Only ever called from a fresh tap in
     the handler below — never from repaint(), never from show_(). */
  function advance() {
    var mine = runId;
    try {
      advTimer = window.setTimeout(function () {
        advTimer = null;
        if (mine !== runId) return;   /* they left; this timer is history */
        go(idx + 1);
      }, ADVANCE_MS);
    } catch (e) { go(idx + 1); }
  }

  /* The delegated tap handler for one screen's option list. `pick` is called
     with the data-k, decides what marking and storing mean for that screen,
     and returns false if the tap changed nothing. `ready` says whether
     Continue may be enabled now. */
  function wire(boxId, screen, goId, pick, ready) {
    var box = el(boxId);
    if (!box) return;
    on(box, "click", function (ev) {
      var t = ev.target;
      try {
        while (t && t !== box && String(t.tagName || "").toLowerCase() !== "button") t = t.parentNode;
      } catch (e) { t = null; }
      if (!t || t === box) return;
      var k = t.getAttribute("data-k");
      if (!k) return;
      /* Only the screen you are on can answer. A hidden screen's button cannot
         be tapped, but nothing about that should be load-bearing. */
      if (SCREENS[idx] !== screen) return;

      /* The dwell is read before the answer is applied, so it measures the
         time the question took rather than the time the marking took. */
      var ms = dwell();
      var took = true;
      try { took = pick(k) !== false; } catch (e2) {}
      /* Their tick now, not last time's. */
      show(knownNode(screen), false);
      if (goId) setGo(goId, !!ready());
      if (!took) return;              /* the cap refused it: not an answer */

      try {
        track("start_answer", {
          step: screen,
          q: QNUM[screen] || 0,
          question: QKEY[screen] || screen,
          answer: clip(k, 100),
          dwell_ms: ms
        });
        answers[screen] = 1;
      } catch (e3) {}

      /* THE ONLY PLACE AN ADVANCE IS EVER SCHEDULED. */
      if (AUTO[screen]) advance();
    });
  }

  /* A single-select screen. Both of them auto-advance. */
  function wireSingle(boxId, screen, field, store) {
    wire(boxId, screen, null,
      function (k) {
        picks[field] = k;
        markOne(boxId, k);
        store(k);
        return true;
      },
      function () { return !!picks[field]; });
  }

  /* ======================================================================
     Screen 5 — the result, in the reader's own answers and their own story.

     Everything below is read back from what they tapped. Where they tapped
     nothing, the markup's own line stands: a summary of defaults nobody chose
     would be putting words in their mouth, which is the same rule the plan
     screen's recap has always followed.
     ====================================================================== */

  function interestLine() {
    var out = [], i, row;
    for (i = 0; i < picks.interests.length; i++) {
      row = q1Row(picks.interests[i]);
      if (row) out.push(row.label);
    }
    if (!out.length) return "";
    var s = out.join(" and ");
    /* Sentence case: the labels are lower case so they read inside a list. */
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  function paintReady() {
    var line = interestLine();
    if (line) text(el("ob-sum-feed"), line);

    if (GOAL_LABEL[picks.goal]) text(el("ob-sum-goal"), GOAL_LABEL[picks.goal]);
    if (MOTIVE_LABEL[picks.motivation]) text(el("ob-sum-why"), MOTIVE_LABEL[picks.motivation]);

    /* Their story, by name. Only when there is one and we know its title — a
       headline reading "Back to ." is worse than the general one. */
    var title = "";
    try { title = (originStack && originStack.title) ? String(originStack.title) : ""; } catch (e) {}
    if (title) {
      /* "Back to X" is a promise only the ending that ACTUALLY ends on the
         story may make. A reader who already pays gets that ending; everyone
         else is being handed to the account step, and for them the true
         sentence is that the story is waiting — with the way back to it on
         the line underneath. */
      text(el("ob-ready-h"), (unlockedNow() && originOpen())
                               ? ("Back to " + title + ".")
                               : (title + " is waiting."));
    }
    paintEnding();
  }

  /* Reaching the result screen is what finishes the onboarding: it is the last
     screen a reader can be on and still be mid-flow, and stamping it is what
     stops /join asking the three questions a second time.

     The sessionStorage marker is the other half of that; the header explains
     what it buys. */
  function enterReady() {
    readyHit = true;
    try { var a = A(); if (a) a.finishOnboarding(); } catch (e) {}
    markReady();
    paintReady();
    track("start_ready", { answers: answerCount() });
  }

  /* ======================================================================
     Wiring, and the doors out.
     ====================================================================== */

  function wireOnce() {
    /* History first, so the very first pushState has somewhere to come back to
       that is ours. */
    try {
      if (window.history && window.history.pushState) {
        window.history.replaceState({ fbs: 0 }, "");
        histOK = true;
      }
    } catch (e) { histOK = false; }

    on(window, "popstate", function (ev) {
      if (!running) return;
      var i = 0;
      try { i = (ev && ev.state && typeof ev.state.fbs === "number") ? ev.state.fbs : 0; }
      catch (e) { i = 0; }
      /* show_ clears the timers first, so a popstate landing mid-advance
         cannot be walked forward by the timer it interrupted. */
      show_(i);
    });

    on(el("ob-back"), "click", back);

    /* The one door to the money side that exists inside the questions, and it
       is on screen 1 only. */
    on(el("ob-signin"), "click", function () {
      try {
        stop();
        if (window.FBJN && window.FBJN.login) window.FBJN.login();
      } catch (e) {}
    });

    /* Q1 · multi-select, one required, two at most. */
    wire("ob-interests-opts", "interests", "ob-interests-go",
      function (k) {
        var took = toggleInterest(k);
        markMany("ob-interests-opts");
        return took;
      },
      function () { return picks.interests.length > 0; });
    on(el("ob-interests-go"), "click", function () { go(idx + 1); });

    /* Q2 and Q3 · single select, both auto-advancing. */
    wireSingle("ob-motivation-opts", "motivation", "motivation", storeMotivation);
    wireSingle("ob-goal-opts", "goal", "goal", storeGoal);

    /* The affirmation's only control. */
    on(el("ob-affirm-go"), "click", function () { go(idx + 1); });

    /* The last button is an <a> straight at the reader's own story, so it
       works with no script at all. The only thing script adds is clearing the
       marker that makes a RELOAD of the result screen land back on it: once
       they have left, a later visit to /join is the plan, not this. */
    on(el("ob-ready-go"), "click", function () { clearReady(); });
    on(el("ob-ready-back"), "click", function () { clearReady(); });

    /* The locked ending. It hands the screen to the money side of this page
       and goes no further: this file does not name a price, a plan or the
       trial, and #jn-you is where that half of the page starts. */
    on(el("ob-ready-buy"), "click", function () {
      try {
        clearReady();
        stop();
        if (window.FBJN && window.FBJN.signup) window.FBJN.signup();
        else if (window.FBJN && window.FBJN.plans) window.FBJN.plans();
      } catch (e) {}
    });

    /* ---- Where the reader walked away -------------------------------------
       The drop-off, question by question. Reported on pagehide and on the tab
       going hidden — the same two moments js/analytics.js's card dwell and
       read.html's stack_dropoff use, because on a phone they are the only
       reliable ones; there is no unload worth trusting in an in-app webview.

       ONCE per page load, and only while the flow never reached the result
       screen. That is the same bargain stack_dropoff makes. */
    function abandon() {
      try {
        if (!running || leftSaid || readyHit) return;
        leftSaid = true;
        var here = SCREENS[idx];
        track("start_abandon", {
          step: here,
          q: QNUM[here] || 0,
          question: QKEY[here] || here,
          dwell_ms: dwell(),
          answers: answerCount()
        });
      } catch (e) {}
    }
    on(window, "pagehide", abandon);
    on(D, "visibilitychange", function () {
      try { if (D.visibilityState === "hidden") abandon(); } catch (e) {}
    });
  }

  /* Anything this browser already said, said back, so nobody answers the same
     question twice. All three come back out of FBA — a refresh mid-flow lands
     the reader on screen 1 with every answer still marked and Continue still
     enabled.

     IT SCHEDULES NOTHING. Marking an answer here is not a tap, and a repaint
     that auto-advanced would walk a returning reader through the flow on its
     own. */
  function repaint() {
    try {
      var a = A();
      if (a) {
        /* Q1 comes back as topic keys and has to be folded back into the four
           groups. A group is on when its FIRST topic is in the record, which
           still holds after js/account.js sheds picks under the byte budget. */
        var ints = a.interests(), i, j;
        if (ints && ints.length) {
          picks.interests = [];
          for (i = 0; i < Q1.length && picks.interests.length < MAX_INTERESTS; i++) {
            for (j = 0; j < ints.length; j++) {
              if (ints[j] === Q1[i].topics[0]) { picks.interests.push(Q1[i].k); break; }
            }
          }
        }
        markMany("ob-interests-opts");

        var g = a.goal();
        if (g > 0 && GOAL_LABEL[String(g)]) {
          picks.goal = String(g);
          markOne("ob-goal-opts", picks.goal);
        }

        if (typeof a.motivation === "function") {
          var m = a.motivation();
          if (m && MOTIVE_LABEL[m]) {
            picks.motivation = m;
            markOne("ob-motivation-opts", m);
          }
        }
      }
    } catch (e) {}

    setGo("ob-interests-go", picks.interests.length > 0);
    paintKnown();
  }

  /* ======================================================================
     window.FBOB — the whole of what the rest of the page may do to this file.
     ====================================================================== */

  var wired = false;

  function boot() {
    if (!wired) { wireOnce(); wired = true; }
    running = true;
    bodyClass("ob-on", true);
    show(el("ob-main"), true);
    origin = findOrigin();
    paintOrigin();
    repaint();
  }

  function fetchIndex() {
    var p = loadIndex();
    if (p && p.then) {
      p.then(function (rows) {
        stacks = rows || null;
        originStack = stackById(origin);
        paintBehind();
        /* Only repaint the screen the new fact is on. */
        if (SCREENS[idx] === "affirm") paintAffirm();
        if (SCREENS[idx] === "ready")  paintReady();
        return null;
      }, function () { return null; });
    }
  }

  function start() {
    try {
      if (!el("ob-stage")) return false;      /* not a page with the screens on it */
      if (running) return true;
      boot();
      /* repaint() has already run inside boot(), so resumeAt() is reading the
         answers as restored rather than as this closure last saw them. */
      show_(resumeAt());
      fetchIndex();
      return true;
    } catch (e) { return false; }
  }

  /* Hand the screen to the money side. Everything here is idempotent: the
     inline block in join.html calls it on paths where the onboarding never
     started at all. */
  function stop() {
    try {
      clearTimers();
      running = false;
      bodyClass("ob-on", false);
      bodyClass("ob-over", false);
      show(el("ob-main"), false);
      /* Hide the individual screens too, not just the box around them. Hiding
         only the container leaves five sections still saying "I am the visible
         one" to anything that reads the attribute rather than the layout —
         which is exactly what the driver did, and it reported a screen that was
         not on the page. Ambiguous state is a bug even when nothing renders
         wrong. */
      for (var i = 0; i < SCREENS.length; i++) show(screenNode(i), false);
    } catch (e) {}
    return true;
  }

  /* The result screen, on its own: Back off the sign-up form, and a reload of
     the result screen itself. Every answer and the story are still on it,
     because both are read back out of the record and the URL rather than held
     in this closure. */
  function resume() {
    try {
      if (!el("ob-stage")) return false;
      if (!running) boot();
      show_(SCREENS.length - 1);
      if (!stacks) fetchIndex();
      return true;
    } catch (e) { return false; }
  }

  try {
    window.FBOB = {
      start: start, stop: stop, resume: resume,
      /* What join.html's router needs and may not work out for itself: was
         this session in the middle of a result screen. */
      pending: pendingReady,
      __factbox: 1
    };
  } catch (e) {}

  /* This file does NOT start itself. join.html's inline block is the router:
     it knows whether this reader has already been through the questions or
     already paid, and it calls start(), resume() or stop() accordingly.
     Exactly one of the two halves of that page is ever on screen, and one
     script decides which — two scripts each deciding for themselves is how a
     page ends up showing both, or neither. */
})();
