#!/usr/bin/env python3
"""Build the three ambient beds added for the 51-stack reader (read.html).

PROVENANCE
==========
Nothing here is sourced. There is no `audio-src/`, no download, no recording,
no third-party file of any kind. Every sample in vault.mp3, wind.mp3 and
reactor.mp3 is generated by ffmpeg's own `anoisesrc` generator and shaped by
ffmpeg's own filters. The only inputs are the seeds and filter constants in
this file, so the output is our own work and the licence is unambiguous.

Run it to regenerate:  ffmpeg -version >= 4.x, then `python3 build-reader-beds.py`
It is idempotent: the noise sources are seeded, so a re-run reproduces the
three files byte for byte.

The 15 beds that were already in this folder are NOT touched by this script.
They are built by ../../build-beds.py from public-domain recordings; see
scenes/AUDIO.md for their provenance.

CONSTRUCTION
============
Same seamless-loop construction as build-beds.py: take L+X seconds of
material and crossfade the trailing X seconds back over the head with
equal-power (quarter-sine) curves. The result is exactly L seconds whose last
sample is the one immediately before its first, so the wrap is continuous by
construction rather than by luck.

Two rules every layer obeys, both from scenes/AUDIO.md:

  * No sustained pure tones. audio-reader.js loops *inside* the file (50 ms in,
    100 ms off the end) to step over MP3 encoder delay and padding, so the wrap
    skips ~150 ms of material. In broadband noise that jump is smaller than the
    signal's own sample-to-sample variation. In a sine it is a click per lap.
    Every "hum" here is therefore a narrow *noise* resonance, not an oscillator.
  * Real energy above 500 Hz. A phone speaker radiates almost nothing below
    that, and two of the shipped beds (door, coil) are near-inaudible on a
    phone for exactly this reason. Each of these three carries a deliberate
    upper layer so that it plays as something rather than as a failed download.

  * Every tremolo rate is >= 0.1 Hz (ffmpeg's minimum) and none of the periods
    divides the loop length, so no layer breathes in step with the wrap.
"""
import subprocess, pathlib, sys, shlex

HERE = pathlib.Path(__file__).parent           # factbox-site/audio
TMP  = HERE / "_reader-bed-tmp"; TMP.mkdir(exist_ok=True)
OUT  = HERE
SR   = 32000

def run(args):
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode:
        print("FFMPEG FAIL:", " ".join(shlex.quote(a) for a in args))
        print(r.stderr[-1800:]); sys.exit(1)

def loop(desc, L, X, pre, out):
    """Synthesise `desc` (a lavfi source), shape it with `pre`, and fold the
    trailing X seconds back over the head to make an exactly-L-second loop."""
    fc = (f"[0:a]aformat=channel_layouts=mono:sample_rates={SR},{pre},asplit=2[p][q];"
          f"[p]atrim=0:{L},asetpts=N/SR/TB,afade=t=in:st=0:d={X}:curve=qsin[a];"
          f"[q]atrim={L}:{L+X},asetpts=N/SR/TB,afade=t=out:st=0:d={X}:curve=qsin,"
          f"apad=whole_dur={L}[b];"
          f"[a][b]amix=inputs=2:normalize=0,atrim=0:{L}[o]")
    run(["ffmpeg", "-hide_banner", "-v", "error", "-y",
         "-f", "lavfi", "-t", str(L + X + 1), "-i", desc,
         "-filter_complex", fc, "-map", "[o]", "-ar", str(SR), "-ac", "1", str(out)])

def mix(layers, out, lufs=-24):
    """layers: [(wav, gain_db)] -> one loudness-normalised mono 48 kbps MP3."""
    args = ["ffmpeg", "-hide_banner", "-v", "error", "-y"]
    for w, _ in layers: args += ["-i", str(w)]
    parts, names = [], []
    for i, (w, g) in enumerate(layers):
        parts.append(f"[{i}:a]volume={g}dB[v{i}]"); names.append(f"[v{i}]")
    parts.append("".join(names) +
                 f"amix=inputs={len(layers)}:normalize=0:duration=shortest,"
                 f"loudnorm=I={lufs}:TP=-3:LRA=11,"
                 f"aformat=sample_rates={SR}:channel_layouts=mono[o]")
    args += ["-filter_complex", ";".join(parts), "-map", "[o]",
             "-c:a", "libmp3lame", "-b:a", "48k", "-ar", str(SR), "-ac", "1",
             "-write_xing", "1", str(out)]
    run(args)

L, X = 22, 3

# ---------------------------------------------------------------------------
# 1. vault — a large, dark stone interior with a long tail.
#    Base bed for church_history and medieval_modern: a council chamber, a
#    cathedral, a trial hall, a cellar. gallery.mp3 is the *bright cool* big
#    room; this is the dark one, a fifth of an octave lower and with a tail
#    roughly twice as long. The two are meant to be told apart.
# ---------------------------------------------------------------------------
loop(f"anoisesrc=c=pink:r={SR}:a=0.55:seed=8201", L, X,
     "highpass=f=85,lowpass=f=1400,lowpass=f=1400,"
     "aecho=0.8:0.88:470|930:0.34|0.24,tremolo=f=0.1:d=0.22", TMP/"vau_a.wav")
loop(f"anoisesrc=c=brown:r={SR}:a=0.65:seed=8202", L, X,
     "bandpass=f=150:width_type=q:w=1.1,tremolo=f=0.11:d=0.3", TMP/"vau_b.wav")
# the layer that survives a phone speaker: stone air, well above 500 Hz
loop(f"anoisesrc=c=pink:r={SR}:a=0.3:seed=8203", L, X,
     "highpass=f=1700,lowpass=f=5400,aecho=0.8:0.8:390|710:0.25|0.15,"
     "tremolo=f=0.13:d=0.4", TMP/"vau_c.wav")
mix([(TMP/"vau_a.wav", 0), (TMP/"vau_b.wav", -8), (TMP/"vau_c.wav", -13)],
    OUT/"vault.mp3", lufs=-25)

# ---------------------------------------------------------------------------
# 2. wind — open, dry, outdoors, no water.
#    Base bed for old_testament and for the outdoor New Testament stacks, and
#    for Genghis Khan's steppe. The low (<220 Hz) layer is deliberately held
#    11 dB down: at -6 the bed measured 4 dB hot at the loop wrap, because a
#    signal that low moves too far between one sample and the next 21.9 s away.
#    Nothing in the shipped fifteen is "outside and
#    dry": sea/harbour are water, palace is a courtyard fountain, everything
#    else is an interior. Two bands drifting at incommensurate rates (0.1 and
#    0.17 Hz) so it moves without ever settling into a pulse you can count.
# ---------------------------------------------------------------------------
loop(f"anoisesrc=c=pink:r={SR}:a=0.6:seed=8301", L, X,
     "highpass=f=170,lowpass=f=2200,tremolo=f=0.1:d=0.5", TMP/"wnd_a.wav")
loop(f"anoisesrc=c=pink:r={SR}:a=0.5:seed=8302", L, X,
     "bandpass=f=700:width_type=q:w=0.7,tremolo=f=0.17:d=0.55", TMP/"wnd_b.wav")
loop(f"anoisesrc=c=brown:r={SR}:a=0.7:seed=8303", L, X,
     "lowpass=f=220,lowpass=f=220,tremolo=f=0.13:d=0.35", TMP/"wnd_c.wav")
# dry grit high up — the difference between "wind" and "a low rumble"
loop(f"anoisesrc=c=pink:r={SR}:a=0.28:seed=8304", L, X,
     "highpass=f=2400,lowpass=f=7200,tremolo=f=0.19:d=0.5", TMP/"wnd_d.wav")
mix([(TMP/"wnd_a.wav", 0), (TMP/"wnd_b.wav", -6), (TMP/"wnd_c.wav", -11),
     (TMP/"wnd_d.wav", -13)], OUT/"wind.mp3", lufs=-24)

# ---------------------------------------------------------------------------
# 3. reactor — a machine room. Cold, continuous, mechanical.
#    Built for the one `disaster` stack (Chernobyl), where every one of the
#    fifteen shipped beds is the wrong century or the wrong planet. Two narrow
#    noise resonances at 55 and 118 Hz stand in for a plant hum without ever
#    being a tone, a mid resonance at 620 Hz gives it a room, and a thin
#    3-9 kHz layer gives it the ventilation hiss that a phone can actually
#    reproduce. Deliberately NO clicks: a Geiger tick on a 22 s loop is a
#    metronome, which is the one thing the loop spec exists to prevent.
# ---------------------------------------------------------------------------
loop(f"anoisesrc=c=brown:r={SR}:a=0.9:seed=8401", L, X,
     "bandpass=f=55:width_type=q:w=2.4,bandpass=f=55:width_type=q:w=2.4,"
     "tremolo=f=0.1:d=0.3", TMP/"rea_a.wav")
loop(f"anoisesrc=c=brown:r={SR}:a=0.9:seed=8402", L, X,
     "bandpass=f=118:width_type=q:w=3.0,bandpass=f=118:width_type=q:w=3.0",
     TMP/"rea_b.wav")
loop(f"anoisesrc=c=pink:r={SR}:a=0.45:seed=8403", L, X,
     "bandpass=f=620:width_type=q:w=1.0,aecho=0.8:0.8:210|430:0.28|0.18,"
     "tremolo=f=0.11:d=0.25", TMP/"rea_c.wav")
loop(f"anoisesrc=c=pink:r={SR}:a=0.3:seed=8404", L, X,
     "highpass=f=3000,lowpass=f=9000,tremolo=f=0.17:d=0.35", TMP/"rea_d.wav")
mix([(TMP/"rea_a.wav", 0), (TMP/"rea_b.wav", -5), (TMP/"rea_c.wav", -9),
     (TMP/"rea_d.wav", -15)], OUT/"reactor.mp3", lufs=-24)

print("built:", ", ".join(str((OUT/f).name) for f in
      ("vault.mp3", "wind.mp3", "reactor.mp3")))
